setGeneric("copynumber",    function(object) standardGeneric("copynumber"))
setGeneric("copynumber<-",  function(object, value) standardGeneric("copynumber<-"))
setGeneric("segmented",     function(object) standardGeneric("segmented"))
setGeneric("segmented<-",   function(object, value) standardGeneric("segmented<-"))
setGeneric("calls",         function(object) standardGeneric("calls"))
setGeneric("calls<-",       function(object, value) standardGeneric("calls<-"))
setGeneric("probloss",      function(object) standardGeneric("probloss"))
setGeneric("probloss<-",    function(object, value) standardGeneric("probloss<-"))
setGeneric("probnorm",      function(object) standardGeneric("probnorm"))
setGeneric("probnorm<-",    function(object, value) standardGeneric("probnorm<-"))
setGeneric("probgain",      function(object) standardGeneric("probgain"))
setGeneric("probgain<-",    function(object, value) standardGeneric("probgain<-"))
setGeneric("probamp",       function(object) standardGeneric("probamp"))
setGeneric("probamp<-",     function(object, value) standardGeneric("probamp<-"))                
setGeneric("chromosomes",   function(object) standardGeneric("chromosomes"))
setGeneric("bpstart",       function(object) standardGeneric("bpstart"))
setGeneric("bpend",         function(object) standardGeneric("bpend"))
setGeneric("plot",          function(x, y, ...) standardGeneric("plot"), useAsDefault=plot)
setGeneric("plot.summary",  function(x, y, ...) standardGeneric("plot.summary"))
